### ISSUE TITLE
Using Triangle to create voronoi and the result is wrong

### ISSUE THREAD

**Issue by Lara1992** [xenovacivus/PathCAM#15]
The input:
22
1 586.3 306.35
2 547.3 306.35 
3 567.034 277.849 
4 508.248 306.35 
5 469.261 306.35 
6 547.235 363.506 
7 566.8 334.928 
8 527.813 334.928 
9 488.813 334.928 
10 605.787 334.928 
11 626.21 306.02 
12 645.06 335.06 
13 722.8 392.15 
14 683.8 392.15 
15 666.64 363.11 
16 625.3 363.55 
17 527.8 277.75 
18 488.8 277.75 
19 449.8 278.19 
20 410.15 277.75 
21 391.3 306.35 
22 430.3 306.35 

The wrong voronoi:
![wrong voronoi](https://cloud.githubusercontent.com/assets/23348727/20123823/009abaaa-a65d-11e6-854c-2d318d9fe733.PNG)

**Comment by Lara1992** [comment]
Another input:
49
1	 281.17  324.959999999998  
2	 133.67  315.809999999998  
3	 91.95  367.130000000005  
4	 109.05  320.15  
5	 240.7  274.940000000002  
6	 158.29  311.459999999998  
7	 182.91  307.119999999995  
8	 181.88  373.259999999998  
9	 157.26  377.6  
10	 132.64  381.940000000002  
11	 108.02  386.280000000005  
12	 116.57  362.790000000002  
13	 141.19  358.45  
14	 165.81  354.109999999998  
15	 190.42  349.769999999995  
16	 174.36  330.609999999998  
17	 149.74  334.95  
18	 125.12  339.290000000002  
19	 215.05  345.419999999995  
20	 198.98  326.269999999995  
21	 223.6  321.930000000005  
22	 248.22  317.590000000002  
23	 256.77  294.1  
24	 281.39  289.759999999998  
25	 232.15  298.440000000002  
26	 207.53  302.780000000005  
27	 323.62  370.380000000005  
28	 255.74  360.230000000005  
29	 231.11  364.569999999995  
30	 239.66  341.080000000005  
31	 206.5  368.909999999998  
32	 222.56  388.069999999995  
33	 247.18  383.730000000005  
34	 311.84  326.940000000002  
35	 312.5  394.190000000002  
36	 296.43  375.040000000002  
37	 271.81  379.390000000002  
38	 304.98  351.55  
39	 280.36  355.890000000002  
40	 264.29  336.740000000002  
41	 272.84  313.25  
42	 362.77  319.380000000005  
43	 338.15  323.719999999995  
44	 371.32  295.880000000005  
45	 322.08  304.559999999998  
46	 337.12  389.85  
47	 345.67  366.359999999998  
48	 329.6  347.209999999998  
49	 354.22  342.869999999995  

![wrong voronoi](https://cloud.githubusercontent.com/assets/23348727/20165868/ce67164c-a74b-11e6-9ead-6c357fc690bd.jpg)

**Comment by xenovacivus** [comment]
Just to clarify, Triangle.NET is an external tool - but it looks like you've been discussing with the right folks to resolve the issue: https://triangle.codeplex.com/discussions/659270.

The C# port may have some bugs from the original version - if you really want to find out if it's a bug in the translation, I'd recommend downloading the original version from here and giving it a go with your values: http://www.cs.cmu.edu/~quake/triangle.html

**Comment by Lara1992** [comment]
Yes, I have found the right one, and the first bug has been solved long ago. I should keep pace with the times. As for the second, a solution has been proposed, and I need to achieve it. Thank you all for your kind help. And it's really helpful - thanks again.
